server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql:///watermark?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&userSSL=false&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
mybatis-plus:
  global-config:
    db-config:
      id-type: auto

